dist: trusty
sudo: required

language: node_js
node_js: "node"

before_install:
 - npm install -g npm

install:
  - npm install

before_script:
  - npm install -g firebase-tools
  - npm install -g grunt
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run testci
  - grunt build

after_success:
  - ./deploy.sh

notifications:
  email:
    on_failure: change
    on_success: change
