sudo: required

language: node_js
node_js: "lts/*"

before_install:
 - npm install -g npm
 - npm install -g yarn

install:
  - yarn install

before_script:
  - npm install -g firebase-tools
  - npm install -g grunt
  - export DISPLAY=:99.0

script:
  - ng test --watch=false
  - yarn run lint
  - grunt build

after_success:
  - ./deploy.sh

notifications:
  email:
    on_failure: change
    on_success: change
