
// THIS IS A GENERATED FILE. USE THE COMMAND 'grunt gen_fortunes' TO REGENERATE

export const fortunes = [
  '.DS_Store',
  '1000.png',
  'already-have-plans.png',
  'bus.png',
  'cantgo.png',
  'carfixed.png',
  'could-be.png',
  'down.png',
  'dts.png',
  'earliest.png',
  'friend.png',
  'harriet.png',
  'inLA.png',
  'kravmaga.png',
  'live.png',
  'nexttime.png',
  'notbackintime.png',
  'notsure.png',
  'ohyah.png',
  'outoftown.png',
  'poop.png',
  'softmaybe.png',
  'solidmaybe.png',
  'tooearly.png',
  'tourist.png',
  'vivek.png',
  'wenthome.png',
  'whoknows.png',
  'wildride.png',
  'wrong.png',
  'yea-fuck-it.png',
];
